from tkinter import*
import sqlite3
import sys
from tkinter import messagebox
from tkinter import ttk
from PIL import ImageTk,Image
import datetime
today=datetime.datetime.now()
now=(today.strftime("%Y-%m-%d"))
yr=(today.strftime("%Y"))



def structure_in():
	root = Tk()
	frame7=Frame(root)
	frame7.grid(row=2,column=2,sticky='n')
	global curr
	frame3_4=Frame(frame7)
	frame3_4.grid(row=0,column=1,sticky='n',padx=220)
	l=Label(frame3_4,text='WORKING CURRENCY',font=('times',13,'bold'))
	l.grid(row=1,column=1,padx=50)
	cur=["UGX","KSH","TSH","USD","EURO","POUND"]
	curr=ttk.Combobox(frame3_4,width=18,font=('times',15),value=cur,state='readonly')
	curr.current(0)
	curr.grid(row=2,column=1,pady=20,padx=50)
	frame7_1=Frame(frame7)
	frame7_1.grid(row=1,column=1,columnspan=5,sticky='n',padx=10,pady=10)
	l=Label(frame7_1,text='CLASS',font=('times',15,'bold'))
	l.grid(row=1,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='NEW ENTRY',font=('times',15,'bold'))
	l.grid(row=1,column=2,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='TERM I',font=('times',15,'bold'))
	l.grid(row=1,column=3,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='TERM II',font=('times',15,'bold'))
	l.grid(row=1,column=4,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='TERM III',font=('times',15,'bold'))
	l.grid(row=1,column=5,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='HOLIDAY',font=('times',15,'bold'))
	l.grid(row=1,column=6,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 1',font=('times',15))
	l.grid(row=2,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 2',font=('times',15))
	l.grid(row=3,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 3',font=('times',15))
	l.grid(row=4,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 4',font=('times',15))
	l.grid(row=5,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 5',font=('times',15))
	l.grid(row=6,column=1,sticky='w',pady=10,padx=10)
	l=Label(frame7_1,text='FORM 6',font=('times',15))
	l.grid(row=7,column=1,sticky='w',pady=10,padx=10)
	f1new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f1new.config(highlightbackground = "black")
	f1new.grid(row=2,column=2,padx=5)
	f1term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f1term1.config(highlightbackground = "black")
	f1term1.grid(row=2,column=3,padx=5)
	f1term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f1term2.config(highlightbackground = "black")
	f1term2.grid(row=2,column=4,padx=5)
	f1term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f1term3.config(highlightbackground = "black")
	f1term3.grid(row=2,column=5,padx=5)
	f1termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f1termh.config(highlightbackground = "black")
	f1termh.grid(row=2,column=6,padx=5)
	f2new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f2new.config(highlightbackground = "black")
	f2new.grid(row=3,column=2,padx=5)
	f2term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f2term1.config(highlightbackground = "black")
	f2term1.grid(row=3,column=3,padx=5)
	f2term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f2term2.config(highlightbackground = "black")
	f2term2.grid(row=3,column=4,padx=5)
	f2term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f2term3.config(highlightbackground = "black")
	f2term3.grid(row=3,column=5,padx=5)
	f2termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f2termh.config(highlightbackground = "black")
	f2termh.grid(row=3,column=6,padx=5)
	f3new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f3new.config(highlightbackground = "black")
	f3new.grid(row=4,column=2,padx=5)
	f3term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f3term1.config(highlightbackground = "black")
	f3term1.grid(row=4,column=3,padx=5)
	f3term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f3term2.config(highlightbackground = "black")
	f3term2.grid(row=4,column=4,padx=5)
	f3term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f3term3.config(highlightbackground = "black")
	f3term3.grid(row=4,column=5,padx=5)
	f3termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f3termh.config(highlightbackground = "black")
	f3termh.grid(row=4,column=6,padx=5)
	f4new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f4new.config(highlightbackground = "black")
	f4new.grid(row=5,column=2,padx=5)
	f4term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f4term1.config(highlightbackground = "black")
	f4term1.grid(row=5,column=3,padx=5)
	f4term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f4term2.config(highlightbackground = "black")
	f4term2.grid(row=5,column=4,padx=5)
	f4term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f4term3.config(highlightbackground = "black")
	f4term3.grid(row=5,column=5,padx=5)
	f4termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f4termh.config(highlightbackground = "black")
	f4termh.grid(row=5,column=6,padx=5)
	f5new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f5new.config(highlightbackground = "black")
	f5new.grid(row=6,column=2,padx=5)
	f5term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f5term1.config(highlightbackground = "black")
	f5term1.grid(row=6,column=3,padx=5)
	f5term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f5term2.config(highlightbackground = "black")
	f5term2.grid(row=6,column=4,padx=5)
	f5term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f5term3.config(highlightbackground = "black")
	f5term3.grid(row=6,column=5,padx=5)
	f5termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f5termh.config(highlightbackground = "black")
	f5termh.grid(row=6,column=6,padx=5)
	f6new=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f6new.config(highlightbackground = "black")
	f6new.grid(row=7,column=2,padx=5)
	f6term1=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f6term1.config(highlightbackground = "black")
	f6term1.grid(row=7,column=3,padx=5)
	f6term2=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f6term2.config(highlightbackground = "black")
	f6term2.grid(row=7,column=4,padx=5)
	f6term3=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f6term3.config(highlightbackground = "black")
	f6term3.grid(row=7,column=5,padx=5)
	f6termh=Entry(frame7_1,width=10,font=('times',15),highlightthickness=1)
	f6termh.config(highlightbackground = "black")
	f6termh.grid(row=7,column=6,padx=5)

	frame7_2=Frame(frame7)
	frame7_2.grid(row=2,column=1,columnspan=5,padx=10,pady=10)
	l=Label(frame7_2,text='FOREX RATES',font=('times',15,'bold'))
	l.grid(row=1,column=1,pady=10,padx=10,columnspan=10)
	lu=Label(frame7_2,text='UGX',font=('times',15))
	lu.grid(row=2,column=1,pady=10,padx=10)
	lk=Label(frame7_2,text='KSH',font=('times',15))
	lk.grid(row=2,column=2,pady=10,padx=10)
	lt=Label(frame7_2,text='TSH',font=('times',15))
	lt.grid(row=2,column=3,pady=10,padx=10)
	la=Label(frame7_2,text='USD',font=('times',15))
	la.grid(row=2,column=4,pady=10,padx=10)
	le=Label(frame7_2,text='EURO',font=('times',15))
	le.grid(row=2,column=5,pady=10,padx=10)
	lp=Label(frame7_2,text='POUND',font=('times',15))
	lp.grid(row=2,column=6,pady=10,padx=10)
	ugx=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	ugx.config(highlightbackground = "black")
	ugx.grid(row=3,column=1,padx=5)
	ksh=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	ksh.config(highlightbackground = "black")
	ksh.grid(row=3,column=2,padx=5)
	tsh=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	tsh.config(highlightbackground = "black")
	tsh.grid(row=3,column=3,padx=5)
	usd=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	usd.config(highlightbackground = "black")
	usd.grid(row=3,column=4,padx=5)
	euro=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	euro.config(highlightbackground = "black")
	euro.grid(row=3,column=5,padx=5)
	pound=Entry(frame7_2,width=10,font=('times',15),highlightthickness=1)
	pound.config(highlightbackground = "black")
	pound.grid(row=3,column=6,padx=5)


	mainloop()

structure_in()